#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

export PYTHONUNBUFFERED=1
export DEPLOYMENT_SOURCE="`pwd`/"

if [ -z "$DEPLOYMENT_INVENTORY" ]; then
    echo "[ERROR] DEPLOYMENT_INVENTORY not set
    exit 1
fi

if [ -z "$DEPLOYMENT_TARGET" ]; then
    echo "[ERROR] DEPLOYMENT_TARGET not set
    exit 1
fi


set -o pipefail
set -o errtrace
set -o nounset
set -o errexit

ansible-playbook -i "$SCRIPT_DIR/inventory/$DEPLOYMENT_INVENTORY" "$SCRIPT_DIR/deploy.yml"
