#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

export PYTHONUNBUFFERED=1
export ANSIBLE_CONFIG="/opt/deployment/ansible.cfg"

if [ -z "$DEPLOYMENT_INVENTORY" ]; then
    echo "[ERROR] DEPLOYMENT_INVENTORY not set"
    exit 1
fi

if [ -z "$DEPLOYMENT_DEPLOY_TO" ]; then
    echo "[ERROR] DEPLOYMENT_DEPLOY_TO not set"
    exit 1
fi

if [ -z "$DEPLOYMENT_DEPLOY_FROM" ]; then
    export DEPLOYMENT_DEPLOY_FROM="$(pwd)"
fi

if [ -z "$DEPLOYMENT_CURRENT_DIR" ]; then
    export DEPLOYMENT_CURRENT_DIR="current"
fi

echo ""
echo ""
echo ""
echo "# Executing Ansible"

exec ansible-playbook -i "$SCRIPT_DIR/inventory/$DEPLOYMENT_INVENTORY" "$SCRIPT_DIR/deploy.yml" $*